### ISSUE TITLE
装不上requirements

### ISSUE THREAD

**Issue by GWillS163** [allwaysLove/SchoolAssignmentManageSystem#9]
总有一个proxy那里被卡住，
报错
`WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/07/3f/a3d687f83c7d44970f70ff0400677746c8860b11f0c08f6b4e07205f0cdc/lazy-object-proxy-1.4.3.tar.gz#sha256=f3900e8a5de27447acbf900b4750b0ddfd7ec1ea7fbaf11dfa911141bc522af0 (from https://pypi.tuna.tsinghua.edu.cn/simple/lazy-object-proxy/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: 'D:\Project\SchoolAssignmentManageSystem-master\venv\Scripts\python.exe' 'D:\Project\SchoolAssignmentManageSystem-master\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\駿清清\AppData\Local\Temp\tmpk9nqzqt8' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement lazy-object-proxy==1.4.3 (from versions: 0.1.0, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.7.0, 1.7.1)
ERROR: No matching distribution found for lazy-object-proxy==1.4.3
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the 'D:\Project\SchoolAssignmentManageSystem-master\venv\Scripts\python.exe -m pip install --upgrade pip' command`

**Comment by GWillS163** [comment]
我的python版本3.10

**Comment by allwaysLove** [comment]
咦，现在是解决了吗？

**Comment by GWillS163** [comment]
> 咦，现在是解决了吗？

屏蔽了版本，强行安装上环境了。现在运行起来啦！但是作业管理界面打不开
![image](https://user-images.githubusercontent.com/49674629/154624960-886a423e-f240-4927-ab74-4d63e9b971b2.png)

**Comment by allwaysLove** [comment]
> > 咦，现在是解决了吗？
> 
> 屏蔽了版本，强行安装上环境了。现在运行起来啦！但是作业管理界面打不开
> ![image](https://user-images.githubusercontent.com/49674629/154624960-886a423e-f240-4927-ab74-4d63e9b971b2.png)
> 

# 创建超级用户（管理员） python manage.py createsuperuser # 依据模型迁移构建数据库表 python manage.py makemigrations python manage.py migrate

这几个命令执行了吗，我写在readme里的

**Comment by GWillS163** [comment]
> > > 咦，现在是解决了吗？
> > 
> > 
> > 屏蔽了版本，强行安装上环境了。现在运行起来啦！但是作业管理界面打不开
> > ![image](https://user-images.githubusercontent.com/49674629/154624960-886a423e-f240-4927-ab74-4d63e9b971b2.png)
> 
> # 创建超级用户（管理员） python manage.py createsuperuser # 依据模型迁移构建数据库表 python manage.py makemigrations python manage.py migrate
> 这几个命令执行了吗，我写在readme里的
是的执行了。

**Comment by GWillS163** [comment]
仍没找到如何通过代码自动新建相应表单，不过暂时自己新建了



在 2022-02-18 13:48:24，"冬酒暖阳" ***@***.***> 写道：

咦，现在是解决了吗？

屏蔽了版本，强行安装上环境了。现在运行起来啦！但是作业管理界面打不开


创建超级用户（管理员） python manage.py createsuperuser # 依据模型迁移构建数据库表 python manage.py makemigrations python manage.py migrate

这几个命令执行了吗，我写在readme里的

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
